name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  dependency-check:
    name: Check for Dependency Updates
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install pip-audit
      run: |
        python -m pip install --upgrade pip
        pip install pip-audit pip-outdated

    - name: Audit dependencies for vulnerabilities
      run: pip-audit --format=json --output=audit-report.json

    - name: Check for outdated packages
      run: |
        pip install -r requirements.txt -r requirements-dev.txt
        pip list --outdated --format=json > outdated-packages.json || true

    - name: Upload audit results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dependency-reports
        path: |
          audit-report.json
          outdated-packages.json