name: Performance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run performance tests weekly
    - cron: '0 6 * * 0'

jobs:
  performance:
    name: Performance Benchmarks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt

    - name: Run performance tests
      run: |
        pytest tests/test_search_performance.py -v --tb=short

    - name: Run basic performance timing
      run: |
        echo "Running application startup timing test..."
        time timeout 15s python -m src.musicrec.main --sample --port 8098 > startup_test.log 2>&1 &
        sleep 5
        curl -s http://localhost:8098 > /dev/null && echo "Startup performance test passed" || echo "Startup test failed"

    - name: Upload performance results
      uses: actions/upload-artifact@v4
      with:
        name: performance-reports
        path: |
          startup_test.log